#spring:
#  h2:
#    console:
#      enabled: 'true'
#      settings:
#        web-allow-others: 'true'
#  datasource:
#    username: sa
#    url: jdbc:h2:mem:testdb
#    password: ''
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: 1234

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: none

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1234

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: none

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379